package com.xujiang.childbodyguard.domain.po;

import java.util.Date;

public class ArticlePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.id
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.title
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.author
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.original_author
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    private String originalAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.icon
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.write_type
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    private Byte writeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.cat_id
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    private Long catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.write_time
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.update_time
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.created_time
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.id
     *
     * @return the value of t_article.id
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.id
     *
     * @param id the value for t_article.id
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.title
     *
     * @return the value of t_article.title
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.title
     *
     * @param title the value for t_article.title
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.author
     *
     * @return the value of t_article.author
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.author
     *
     * @param author the value for t_article.author
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.original_author
     *
     * @return the value of t_article.original_author
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public String getOriginalAuthor() {
        return originalAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.original_author
     *
     * @param originalAuthor the value for t_article.original_author
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public void setOriginalAuthor(String originalAuthor) {
        this.originalAuthor = originalAuthor == null ? null : originalAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.icon
     *
     * @return the value of t_article.icon
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.icon
     *
     * @param icon the value for t_article.icon
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.write_type
     *
     * @return the value of t_article.write_type
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public Byte getWriteType() {
        return writeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.write_type
     *
     * @param writeType the value for t_article.write_type
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public void setWriteType(Byte writeType) {
        this.writeType = writeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.cat_id
     *
     * @return the value of t_article.cat_id
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public Long getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.cat_id
     *
     * @param catId the value for t_article.cat_id
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public void setCatId(Long catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.write_time
     *
     * @return the value of t_article.write_time
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.write_time
     *
     * @param writeTime the value for t_article.write_time
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.update_time
     *
     * @return the value of t_article.update_time
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.update_time
     *
     * @param updateTime the value for t_article.update_time
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.created_time
     *
     * @return the value of t_article.created_time
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.created_time
     *
     * @param createdTime the value for t_article.created_time
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ArticlePO other = (ArticlePO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getAuthor() == null ? other.getAuthor() == null : this.getAuthor().equals(other.getAuthor()))
            && (this.getOriginalAuthor() == null ? other.getOriginalAuthor() == null : this.getOriginalAuthor().equals(other.getOriginalAuthor()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getWriteType() == null ? other.getWriteType() == null : this.getWriteType().equals(other.getWriteType()))
            && (this.getCatId() == null ? other.getCatId() == null : this.getCatId().equals(other.getCatId()))
            && (this.getWriteTime() == null ? other.getWriteTime() == null : this.getWriteTime().equals(other.getWriteTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getAuthor() == null) ? 0 : getAuthor().hashCode());
        result = prime * result + ((getOriginalAuthor() == null) ? 0 : getOriginalAuthor().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getWriteType() == null) ? 0 : getWriteType().hashCode());
        result = prime * result + ((getCatId() == null) ? 0 : getCatId().hashCode());
        result = prime * result + ((getWriteTime() == null) ? 0 : getWriteTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Sat Jun 23 19:22:02 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", author=").append(author);
        sb.append(", originalAuthor=").append(originalAuthor);
        sb.append(", icon=").append(icon);
        sb.append(", writeType=").append(writeType);
        sb.append(", catId=").append(catId);
        sb.append(", writeTime=").append(writeTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createdTime=").append(createdTime);
        sb.append("]");
        return sb.toString();
    }
}